In [1]:
# import Dependencies
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import re
from sqlalchemy import create_engine
import psycopg2

In [2]:
# create a function that can be reused for scraping the data
def get_html_data(url):
    response = requests.get(url)
    return BeautifulSoup(response.text, "html5lib")

### Source: The Washington Post

* http://stats.washingtonpost.com/fb/glossary.asp

In [3]:
player_position_url = 'http://stats.washingtonpost.com/fb/glossary.asp'

pp_response = get_html_data(player_position_url)
# print(pp_response.prettify())

In [4]:
# results are returned as an iterable list
pp_results = pp_response.find_all('table', class_="shsTable")

# print(pp_results)
# print(pp_results[1].prettify())   

pp_df = pd.read_html(str(pp_results[1]))
pp_df = pp_df[0]
pp_df.head()

                        0                       1
0  Position Abbreviations  Position Abbreviations
1            Abbreviation                Position
2                      QB             Quarterback
3                      RB            Running Back
4                      FB                Fullback

In [5]:
# rename columns
pp_df = pp_df.rename(columns={0: "abbreviation", 1 : "position"}) 

# set index to abbreviation
pp_df.set_index("abbreviation", inplace=True)
pp_df.drop(['Position Abbreviations', 'Abbreviation'], inplace=True)

pp_df.head()

                   position
abbreviation
QB              Quarterback
RB             Running Back
FB                 Fullback
WR            Wide Receiver
TE                Tight End

### Super Bowl Winners
### Source: Topend Sports
* The Super Bowl is the annual championship game of the National Football League (NFL). 
* Below is a list of all the winners of the Super Bowl since Green Bay won the first in 1967. 
* The years listed indicate the year the Super Bowl was played, the regular season is played during the year before.

In [6]:
# Superbowl winning teams with scores 
sb_url = 'https://www.topendsports.com/events/super-bowl/winners-list.htm'
sb_response = get_html_data(sb_url)

# print(sb_response.prettify())

In [7]:
# results are returned as an iterable list
sb_results = sb_response.find_all('table', class_="list")

# print(sb_results[0].prettify())

# read html to convert the data to dataframe - but this return a list
sb_df = pd.read_html(str(sb_results))

# convert the list to a dataframe
sb_df = sb_df[0]

# display the first 5 rows of dataframe
sb_df.head()

   Year   No.                Winner            Opposition  Score       Venue
0  2020   LIV    Kansas City Chiefs   San Francisco 49ers  31-20       Miami
1  2019  LIII  New England Patriots      Los Angeles Rams   13-3     Atlanta
2  2018   LII   Philadelphia Eagles  New England Patriots  41-33   Minnesota
3  2017    LI  New England Patriots       Atlanta Falcons  34-28       Texas
4  2016     L        Denver Broncos     Carolina Panthers  24-10  California

In [8]:
# rename columns
sb_df = sb_df.rename(columns={'Year' : 'year',
                              'No.' : 'sb_no', 
                              'Winner': "winner_team", 
                              "Opposition" : "loser_team"                              
                              }) 
sb_df.head(12)

,year,sb_no,winner_team,loser_team,Score,Venue
0,2020,LIV,Kansas City Chiefs,San Francisco 49ers,31-20,Miami
1,2019,LIII,New England Patriots,Los Angeles Rams,13-3,Atlanta
2,2018,LII,Philadelphia Eagles,New England Patriots,41-33,Minnesota
3,2017,LI,New England Patriots,Atlanta Falcons,34-28,Texas
4,2016,L,Denver Broncos,Carolina Panthers,24-10,California
5,2015,XLIX,New England Patriots,Seattle Seahawks,28-24,Arizona
6,2014,XLVIII,Seattle Seahawks,Denver Broncos,43-8,New Jersey
7,2013,XLVII,Baltimore Ravens,San Francisco 49ers,34-31,New Orleans
8,2012,XLVI,New York Giants,New England Patriots,21-17,Indianapolis
9,2011,XLV,Green Bay Packers,Pittsburgh Steelers,31-25,Texas
10,2010,XLIV,New Orleans Saints,Indianapolis Colts,31â17,Miami
11,2009,XLIII,Pittsburgh Steelers,Arizona Cardinals,27-23,Tampa

In [9]:
# Data has some special characters in Score field we need to clean up all the special characters except '-' 
# for splittig the score into winner and loser score

sb_df['Score'] = sb_df['Score'].str.replace(r"[^0-9]+", '-')
sb_df.head(12)

,year,sb_no,winner_team,loser_team,Score,Venue
0,2020,LIV,Kansas City Chiefs,San Francisco 49ers,31-20,Miami
1,2019,LIII,New England Patriots,Los Angeles Rams,13-3,Atlanta
2,2018,LII,Philadelphia Eagles,New England Patriots,41-33,Minnesota
3,2017,LI,New England Patriots,Atlanta Falcons,34-28,Texas
4,2016,L,Denver Broncos,Carolina Panthers,24-10,California
5,2015,XLIX,New England Patriots,Seattle Seahawks,28-24,Arizona
6,2014,XLVIII,Seattle Seahawks,Denver Broncos,43-8,New Jersey
7,2013,XLVII,Baltimore Ravens,San Francisco 49ers,34-31,New Orleans
8,2012,XLVI,New York Giants,New England Patriots,21-17,Indianapolis
9,2011,XLV,Green Bay Packers,Pittsburgh Steelers,31-25,Texas
10,2010,XLIV,New Orleans Saints,Indianapolis Colts,31-17,Miami
11,2009,XLIII,Pittsburgh Steelers,Arizona Cardinals,27-23,Tampa

In [10]:
# split the score in to 2 fields: score_won and score_lost
def get_winner_score(Score):
    return Score.split("-")[0]

def get_loser_score(Score):
    return Score.split("-")[1]

# Use the labda function to apply the above function to split the score in the dataframe
sb_df['winner_score'] = sb_df['Score'].apply(lambda x: f"{get_winner_score(x)}")
sb_df['loser_score'] = sb_df['Score'].apply(lambda x: f"{get_loser_score(x)}")

#drop columns that are not needed
sb_df.drop(['Score', 'Venue'],axis='columns',inplace=True)

# set index to sb_no 
sb_df.set_index("sb_no", inplace=True)

# rearrange the columns
sb_df = sb_df[['year', 'winner_team', 'winner_score', 'loser_team', 'loser_score']]

sb_df.head()

,year,winner_team,winner_score,loser_team,loser_score
sb_no,,,,,
LIV,2020,Kansas City Chiefs,31,San Francisco 49ers,20
LIII,2019,New England Patriots,13,Los Angeles Rams,3
LII,2018,Philadelphia Eagles,41,New England Patriots,33
LI,2017,New England Patriots,34,Atlanta Falcons,28
L,2016,Denver Broncos,24,Carolina Panthers,10

### Source: ESPN
### NFL History - Super Bowl MVPs
* http://www.espn.com/nfl/superbowl/history/mvps

In [11]:
mvp_url = 'http://www.espn.com/nfl/superbowl/history/mvps'
mvp_response = get_html_data(mvp_url)
# print(mvp_response.prettify())

In [12]:
# results are returned as an iterable list
mvp_results = mvp_response.find_all('table', class_="tablehead")

# print(mvp_results[0].prettify())      

# read html and convert it to pandas dataframe
mvp_df = pd.read_html(str(mvp_results))
mvp_df = mvp_df[0]

# rename columns
mvp_df = mvp_df.rename(columns={0: "sb_no", 1 : "mv_player", 2 : "highlights"}) 

# set the value 50 to letter L to be consistent with other super bowl numbers
mvp_df['sb_no'] = mvp_df['sb_no'].replace('50','L', regex=True)
mvp_df.head()

,sb_no,mv_player,highlights
0,Super Bowl Most Valuable Players,Super Bowl Most Valuable Players,Super Bowl Most Valuable Players
1,NO.,PLAYER,HIGHLIGHTS
2,I,"Bart Starr, QB, Green Bay",Two touchdown passes
3,II,"Bart Starr, QB, Green Bay","202 yards passing, 1 TD"
4,III,"Joe Namath, QB, New York Jets",206 yards passing

In [13]:
# set index to sb_no
mvp_df.set_index("sb_no", inplace=True)

# drop the unwanted data
mvp_df.drop(['Super Bowl Most Valuable Players', 'NO.'], inplace=True)

#dispaly the data
mvp_df.head()

                           mv_player                          highlights
sb_no
I          Bart Starr, QB, Green Bay                Two touchdown passes
II         Bart Starr, QB, Green Bay             202 yards passing, 1 TD
III    Joe Namath, QB, New York Jets                   206 yards passing
IV       Len Dawson, QB, Kansas City             142 yards passing, 1 TD
V           Chuck Howley, LB, Dallas  Two interceptions, fumble recovery

In [14]:
# Split the mvp_player column into name of the player, role, and the team
def get_player(mv_player):
    return mv_player.split(",")[0]

def get_position(mv_player):
    return mv_player.split(",")[1]

def get_team(mv_player):
    return mv_player.split(",")[2]

mvp_df['player'] = mvp_df['mv_player'].apply(lambda x: f"{get_player(x)}")
mvp_df['position_abbr'] = mvp_df['mv_player'].apply(lambda x: f"{get_position(x)}")
mvp_df['team'] = mvp_df['mv_player'].apply(lambda x: f"{get_team(x)}")

# drop mv_player
mvp_df.drop(['mv_player'],axis='columns',inplace=True)

# Rearrange the columns
mvp_df = mvp_df[['player', 'position_abbr', 'team', 'highlights']]

# Display the data
mvp_df.head()

,player,position_abbr,team,highlights
sb_no,,,,
I,Bart Starr,QB,Green Bay,Two touchdown passes
II,Bart Starr,QB,Green Bay,"202 yards passing, 1 TD"
III,Joe Namath,QB,New York Jets,206 yards passing
IV,Len Dawson,QB,Kansas City,"142 yards passing, 1 TD"
V,Chuck Howley,LB,Dallas,"Two interceptions, fumble recovery"

### Source: Wikipedia
### List of Super Bowl starting quarterbacks
* https://en.wikipedia.org/wiki/List_of_Super_Bowl_starting_quarterbacks

In [15]:
qb_url = 'https://en.wikipedia.org/wiki/List_of_Super_Bowl_starting_quarterbacks'

qb_response = get_html_data(qb_url)
# print(qb_response.prettify())

In [16]:
# results are returned as an iterable list
qb_results = qb_response.find_all('table', class_="wikitable")

# print(qb_results[1].prettify())      

qb_df = pd.read_html(str(qb_results[1]))
qb_df = qb_df[0]
qb_df.head()

,Season,Super Bowl,Winning QB,Team,Losing QB,Team.1
0,1966 AFL/NFL,I,Bart Starr*MVP,Green Bay Packersn,Len Dawson*,Kansas City Chiefsa
1,1967 AFL/NFL,II,Bart Starr*MVP,Green Bay Packersn,Daryle Lamonica,Oakland Raidersa
2,1968 AFL/NFL,III,Joe Namath*MVP,New York Jetsa,Earl Morrall,Baltimore Coltsn
3,1969 AFL/NFL,IV,Len Dawson*MVP,Kansas City Chiefsa,Joe Kapp,Minnesota Vikingsn
4,1970,V,Johnny Unitas*,Baltimore ColtsA,Craig Morton,Dallas CowboysN

In [17]:
# remove AFL/NFL from the season column and make sure the length of the year of 4
qb_df['Season'] = qb_df['Season'].str[:4]
qb_df['Season'].astype(str).map(len).head()

0    4
1    4
2    4
3    4
4    4
Name: Season, dtype: int64

In [18]:
# remove all the non-word charachaters from the winning QB and losing QB columns

qb_df['Winning QB'] = qb_df['Winning QB'].str.replace('\W', ' ')
qb_df['Losing QB'] = qb_df['Losing QB'].str.replace('\W', ' ')
qb_df.head()

,Season,Super Bowl,Winning QB,Team,Losing QB,Team.1
0,1966,I,Bart Starr MVP,Green Bay Packersn,Len Dawson,Kansas City Chiefsa
1,1967,II,Bart Starr MVP,Green Bay Packersn,Daryle Lamonica,Oakland Raidersa
2,1968,III,Joe Namath MVP,New York Jetsa,Earl Morrall,Baltimore Coltsn
3,1969,IV,Len Dawson MVP,Kansas City Chiefsa,Joe Kapp,Minnesota Vikingsn
4,1970,V,Johnny Unitas,Baltimore ColtsA,Craig Morton,Dallas CowboysN

In [19]:
# if last 3 characters of the winning qb is MVP then move it to the new column is_mvp then remove it from winning qb column

qb_df['also_mvp'] = np.where(qb_df['Winning QB'].str[-3:] == 'MVP', 'MVP', '') 
qb_df['Winning QB'] = qb_df['Winning QB'].str.replace('MVP','', regex=True)
qb_df.head()

,Season,Super Bowl,Winning QB,Team,Losing QB,Team.1,also_mvp
0,1966,I,Bart Starr,Green Bay Packersn,Len Dawson,Kansas City Chiefsa,MVP
1,1967,II,Bart Starr,Green Bay Packersn,Daryle Lamonica,Oakland Raidersa,MVP
2,1968,III,Joe Namath,New York Jetsa,Earl Morrall,Baltimore Coltsn,MVP
3,1969,IV,Len Dawson,Kansas City Chiefsa,Joe Kapp,Minnesota Vikingsn,MVP
4,1970,V,Johnny Unitas,Baltimore ColtsA,Craig Morton,Dallas CowboysN,

In [20]:
# rename columns
qb_df = qb_df.rename(columns={"Season" : "year", 
                              "Super Bowl" : 'sb_no',
                              'Winning QB' : 'winner_qb',
                              'Team': "winner_team", 
                              'Losing QB' : 'loser_qb',
                              "Team.1" : "loser_team"}) 
qb_df.head()

,year,sb_no,winner_qb,winner_team,loser_qb,loser_team,also_mvp
0,1966,I,Bart Starr,Green Bay Packersn,Len Dawson,Kansas City Chiefsa,MVP
1,1967,II,Bart Starr,Green Bay Packersn,Daryle Lamonica,Oakland Raidersa,MVP
2,1968,III,Joe Namath,New York Jetsa,Earl Morrall,Baltimore Coltsn,MVP
3,1969,IV,Len Dawson,Kansas City Chiefsa,Joe Kapp,Minnesota Vikingsn,MVP
4,1970,V,Johnny Unitas,Baltimore ColtsA,Craig Morton,Dallas CowboysN,

In [21]:
# the last character of the team name has 'a' or 'n' to nitity afc or nfc. 
# map a to 'AFC', n to 'NFC' then remove that extra character from team names

qb_df['winner_conf'] = np.where(qb_df['winner_team'].str[-1].str.lower() == 'a', 'AFC', 'NFC') 
qb_df['loser_conf'] = np.where(qb_df['loser_team'].str[-1].str.lower() == 'a', 'AFC', 'NFC')

qb_df['winner_team'] = [sub[ : -1] for sub in qb_df['winner_team']] 
qb_df['loser_team'] = [sub[ : -1] for sub in qb_df['loser_team']]

# Update the super bowl number 50 to L
qb_df['sb_no'] = qb_df['sb_no'].replace('50','L', regex=True)

qb_df.head()

,year,sb_no,winner_qb,winner_team,loser_qb,loser_team,also_mvp,winner_conf,loser_conf
0,1966,I,Bart Starr,Green Bay Packers,Len Dawson,Kansas City Chiefs,MVP,NFC,AFC
1,1967,II,Bart Starr,Green Bay Packers,Daryle Lamonica,Oakland Raiders,MVP,NFC,AFC
2,1968,III,Joe Namath,New York Jets,Earl Morrall,Baltimore Colts,MVP,AFC,NFC
3,1969,IV,Len Dawson,Kansas City Chiefs,Joe Kapp,Minnesota Vikings,MVP,AFC,NFC
4,1970,V,Johnny Unitas,Baltimore Colts,Craig Morton,Dallas Cowboys,,AFC,NFC

In [22]:
# Rearrange the columns
qb_df = qb_df[['sb_no', 'year', 'winner_conf', 'winner_team', 'winner_qb', 'also_mvp', \
               'loser_conf', 'loser_team', 'loser_qb']]

qb_df.head()

,sb_no,year,winner_conf,winner_team,winner_qb,also_mvp,loser_conf,loser_team,loser_qb
0,I,1966,NFC,Green Bay Packers,Bart Starr,MVP,AFC,Kansas City Chiefs,Len Dawson
1,II,1967,NFC,Green Bay Packers,Bart Starr,MVP,AFC,Oakland Raiders,Daryle Lamonica
2,III,1968,AFC,New York Jets,Joe Namath,MVP,NFC,Baltimore Colts,Earl Morrall
3,IV,1969,AFC,Kansas City Chiefs,Len Dawson,MVP,NFC,Minnesota Vikings,Joe Kapp
4,V,1970,AFC,Baltimore Colts,Johnny Unitas,,NFC,Dallas Cowboys,Craig Morton

In [23]:
# set index to sb_no
qb_df.set_index("sb_no", inplace=True)
qb_df.tail()

,year,winner_conf,winner_team,winner_qb,also_mvp,loser_conf,loser_team,loser_qb
sb_no,,,,,,,,
LI,2016,AFC,New England Patriots,Tom Brady,MVP,NFC,Atlanta Falcons,Matt Ryan
LII,2017,NFC,Philadelphia Eagles,Nick Foles,MVP,AFC,New England Patriots,Tom Brady
LIII,2018,AFC,New England Patriots,Tom Brady,,NFC,Los Angeles Rams,Jared Goff
LIV,2019,AFC,Kansas City Chiefs,Patrick Mahomes,MVP,NFC,San Francisco 49ers,Jimmy Garoppolo
Super Bowl,Seas,NFC,Tea,Winning QB,,NFC,Tea,Losing QB

In [24]:
qb_df.drop(['Super Bowl'], inplace=True)
#dispaly the data
qb_df.tail()

,year,winner_conf,winner_team,winner_qb,also_mvp,loser_conf,loser_team,loser_qb
sb_no,,,,,,,,
L,2015,AFC,Denver Broncos,Peyton Manning,,NFC,Carolina Panthers,Cam Newton
LI,2016,AFC,New England Patriots,Tom Brady,MVP,NFC,Atlanta Falcons,Matt Ryan
LII,2017,NFC,Philadelphia Eagles,Nick Foles,MVP,AFC,New England Patriots,Tom Brady
LIII,2018,AFC,New England Patriots,Tom Brady,,NFC,Los Angeles Rams,Jared Goff
LIV,2019,AFC,Kansas City Chiefs,Patrick Mahomes,MVP,NFC,San Francisco 49ers,Jimmy Garoppolo

### Create database connection

In [25]:
connection_string = "postgres:postgres@localhost:5432/nfl_db"
engine = create_engine(f'postgresql://{connection_string}')

### Load DataFrames into database

In [26]:
pp_df.to_sql(name='player_position', con=engine, if_exists='replace', index=True)

In [27]:
sb_df.to_sql(name='sb_winners', con=engine, if_exists='replace', index=True)

In [28]:
mvp_df.to_sql(name='most_valuable_player', con=engine, if_exists='replace', index=True)

In [29]:
qb_df.to_sql(name='sb_quarterbacks', con=engine, if_exists='replace', index=True)

In [30]:
engine = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/nfl_db')
connection = engine.connect()

In [31]:
query = '''
    select *
      from mvp_position
      ;
'''
mvp_position_df = pd.read_sql_query(query, engine)
mvp_position_df.tail()

,team,sb_no,player,position_abbr,position,highlights
49,Baltimore,XXXV,Ray Lewis,LB,Linebacker,Led a dominant Ravens defense
50,Dallas,V,Chuck Howley,LB,Linebacker,"Two interceptions, fumble recovery"
51,Tampa Bay,XXXVII,Dexter Jackson,CB,Cornerback,Two first-half interceptions
52,Dallas,XXX,Larry Brown,CB,Cornerback,Two interceptions
53,Miami,VII,Jake Scott,S,Safety,Two interceptions

In [32]:
superbowl_query = '''
drop table if exists superbowl restrict;
create table superbowl as(
select sb.sb_no, 
       sb.year, 
       qb.winner_conf, 
       wd.winner_div, 
       trim(qb.winner_team) as winner_team, 
       sb.winner_score, 
       trim(qb.winner_qb) as winner_qb, 
       qb.also_mvp, 
       trim(s.stadium) as stadium, 
       trim(st.city) as city, 
       trim(st.state) as state,
       qb.loser_conf, 
       ld.loser_div, 
       trim(qb.loser_team) as loser_team, 
       sb.loser_score, 
       trim(qb.loser_qb) as loser_qb
  from sb_winners sb, 
       sb_quarterbacks qb, 
       winner_div as wd, 
       loser_div as ld, 
       scores as s, 
       stadiums as st
 where trim(sb.sb_no) = trim(qb.sb_no)
   and trim(qb.sb_no) = trim(wd.sb_no)
   and trim(qb.sb_no) = trim(ld.sb_no)
   and lower(trim(qb.winner_team)) = lower(trim(wd.winner_team))
   and lower(trim(qb.loser_team)) = lower(trim(ld.loser_team))
   and (sb.year - 1) = s.schedule_season
   and lower(trim(s.schedule_week)) = 'superbowl'
   and lower(trim(s.stadium)) = lower(trim(st.stadium_name))
   order by year desc);
select * from superbowl;
   '''
sb_final_df = pd.read_sql_query(superbowl_query, engine)
sb_final_df

,sb_no,year,winner_conf,winner_div,winner_team,winner_score,winner_qb,also_mvp,stadium,city,state,loser_conf,loser_div,loser_team,loser_score,loser_qb
0,LIV,2020,AFC,AFC West,Kansas City Chiefs,31,Patrick Mahomes,MVP,Hard Rock Stadium,Miami Gardens,FL,NFC,NFC West,San Francisco 49ers,20,Jimmy Garoppolo
1,LII,2018,NFC,NFC East,Philadelphia Eagles,41,Nick Foles,MVP,U.S. Bank Stadium,Minneapolis,MN,AFC,AFC East,New England Patriots,33,Tom Brady
2,LI,2017,AFC,AFC East,New England Patriots,34,Tom Brady,MVP,NRG Stadium,Houston,TX,NFC,NFC South,Atlanta Falcons,28,Matt Ryan
3,L,2016,AFC,AFC West,Denver Broncos,24,Peyton Manning,,Levi's Stadium,Santa Clara,CA,NFC,NFC South,Carolina Panthers,10,Cam Newton
4,XLIX,2015,AFC,AFC East,New England Patriots,28,Tom Brady,MVP,University of Phoenix Stadium,Glendale,AZ,NFC,NFC West,Seattle Seahawks,24,Russell Wilson
5,XLVIII,2014,NFC,NFC West,Seattle Seahawks,43,Russell Wilson,,MetLife Stadium,East Rutherford,NJ,AFC,AFC West,Denver Broncos,8,Peyton Manning
6,XLVII,2013,AFC,AFC North,Baltimore Ravens,34,Joe Flacco,MVP,Mercedes-Benz Superdome,New Orleans,LA,NFC,NFC West,San Francisco 49ers,31,Colin Kaepernick
7,XLVI,2012,NFC,NFC East,New York Giants,21,Eli Manning,MVP,Lucas Oil Stadium,Indianapolis,IN,AFC,AFC East,New England Patriots,17,Tom Brady
8,XLV,2011,NFC,NFC North,Green Bay Packers,31,Aaron Rodgers,MVP,Cowboys Stadium,Arlington,TX,AFC,AFC North,Pittsburgh Steelers,25,Ben Roethlisberger
9,XLIV,2010,NFC,NFC South,New Orleans Saints,31,Drew Brees,MVP,Sun Life Stadium,Miami Gardens,FL,AFC,AFC South,Indianapolis Colts,17,Peyton Manning
10,XLIII,2009,AFC,AFC North,Pittsburgh Steelers,27,Ben Roethlisberger,,Raymond James Stadium,Tampa,FL,NFC,NFC West,Arizona Cardinals,23,Kurt Warner
11,XLII,2008,NFC,NFC East,New York Giants,17,Eli Manning,MVP,University of Phoenix Stadium,Glendale,AZ,AFC,AFC East,New England Patriots,14,Tom Brady
12,XLI,2007,AFC,AFC South,Indianapolis Colts,29,Peyton Manning,MVP,Dolphin Stadium,Miami,FL,NFC,NFC North,Chicago Bears,17,Rex Grossman
13,XL,2006,AFC,AFC North,Pittsburgh Steelers,21,Ben Roethlisberger,,Ford Field,Detroit,MI,NFC,NFC West,Seattle Seahawks,10,Matt Hasselbeck
14,XXXIX,2005,AFC,AFC East,New England Patriots,24,Tom Brady,,Alltel Stadium,Jacksonville,FL,NFC,NFC East,Philadelphia Eagles,21,Donovan McNabb
15,XXXVIII,2004,AFC,AFC East,New England Patriots,32,Tom Brady,MVP,Reliant Stadium,Houston,TX,NFC,NFC South,Carolina Panthers,29,Jake Delhomme
16,XXXVII,2003,NFC,NFC South,Tampa Bay Buccaneers,48,Brad Johnson,,Qualcomm Stadium,San Diego,CA,AFC,AFC West,Oakland Raiders,21,Rich Gannon
17,XXXVI,2002,AFC,AFC East,New England Patriots,20,Tom Brady,MVP,Louisiana Superdome,New Orleans,LA,NFC,,St. Louis Rams,17,Kurt Warner
18,XXXV,2001,AFC,AFC North,Baltimore Ravens,34,Trent Dilfer,,Raymond James Stadium,Tampa,FL,NFC,NFC East,New York Giants,7,Kerry Collins
19,XXXIV,2000,NFC,,St. Louis Rams,23,Kurt Warner,MVP,Georgia Dome,Atlanta,GA,AFC,AFC South,Tennessee Titans,16,Steve McNair
20,XXXIII,1999,AFC,AFC West,Denver Broncos,34,John Elway,MVP,Pro Player Stadium,Miami,FL,NFC,NFC South,Atlanta Falcons,19,Chris Chandler
21,XXXII,1998,AFC,AFC West,Denver Broncos,31,John Elway,,Qualcomm Stadium,San Diego,CA,NFC,NFC North,Green Bay Packers,24,Brett Favre
22,XXXI,1997,NFC,NFC North,Green Bay Packers,35,Brett Favre,,Louisiana Superdome,New Orleans,LA,AFC,AFC East,New England Patriots,21,Drew Bledsoe
23,XXX,1996,NFC,NFC East,Dallas Cowboys,27,Troy Aikman,,Sun Devil Stadium,Tempe,AZ,AFC,AFC North,Pittsburgh Steelers,17,Neil O Donnell
24,XXIX,1995,NFC,NFC West,San Francisco 49ers,49,Steve Young,MVP,Joe Robbie Stadium,Miami,FL,AFC,AFC West,San Diego Chargers,26,Stan Humphries
25,XXVIII,1994,NFC,NFC East,Dallas Cowboys,30,Troy Aikman,,Georgia Dome,Atlanta,GA,AFC,AFC East,Buffalo Bills,13,Jim Kelly
26,XXVII,1993,NFC,NFC East,Dallas Cowboys,52,Troy Aikman,MVP,Rose Bowl,Pasadena,CA,AFC,AFC East,Buffalo Bills,17,Jim Kelly
27,XXVI,1992,NFC,NFC East,Washington Redskins,37,Mark Rypien,MVP,Hubert H. Humphrey Metrodome,Minneapolis,MN,AFC,AFC East,Buffalo Bills,24,Jim Kelly
28,XXV,1991,NFC,NFC East,New York Giants,20,Jeff Hostetler,,Tampa Stadium,Tampa,FL,AFC,AFC East,Buffalo Bills,19,Jim Kelly
29,XXIV,1990,NFC,NFC West,San Francisco 49ers,55,Joe Montana,MVP,Louisiana Superdome,New Orleans,LA,AFC,AFC West,Denver Broncos,10,John Elway
30,XXIII,1989,NFC,NFC West,San Francisco 49ers,20,Joe Montana,,Joe Robbie Stadium,Miami,FL,AFC,AFC North,Cincinnati Bengals,16,Boomer Esiason
31,XXII,1988,NFC,NFC East,Washington Redskins,42,Doug Williams,MVP,Jack Murphy Stadium,San Diego,CA,AFC,AFC West,Denver Broncos,10,John Elway
32,XXI,1987,NFC,NFC East,New York Giants,39,Phil Simms,MVP,Rose Bowl,Pasadena,CA,AFC,AFC West,Denver Broncos,20,John Elway
33,XX,1986,NFC,NFC North,Chicago Bears,46,Jim McMahon,,Louisiana Superdome,New Orleans,LA,AFC,AFC East,New England Patriots,10,Tony Eason
34,XIX,1985,NFC,NFC West,San Francisco 49ers,38,Joe Montana,MVP,Stanford Stadium,Palo Alto,CA,AFC,AFC East,Miami Dolphins,16,Dan Marino
35,XVIII,1984,AFC,,Los Angeles Raiders,38,Jim Plunkett,,Tampa Stadium,Tampa,FL,NFC,NFC East,Washington Redskins,9,Joe Theismann
36,XVII,1983,NFC,NFC East,Washington Redskins,27,Joe Theismann,,Rose Bowl,Pasadena,CA,AFC,AFC East,Miami Dolphins,17,David Woodley
37,XVI,1982,NFC,NFC West,San Francisco 49ers,26,Joe Montana,MVP,Pontiac Silverdome,Pontiac,MI,AFC,AFC North,Cincinnati Bengals,21,Ken Anderson
38,XV,1981,AFC,AFC West,Oakland Raiders,27,Jim Plunkett,MVP,Louisiana Superdome,New Orleans,LA,NFC,NFC East,Philadelphia Eagles,10,Ron Jaworski
39,XIV,1980,AFC,AFC North,Pittsburgh Steelers,31,Terry Bradshaw,MVP,Rose Bowl,Pasadena,CA,NFC,NFC West,Los Angeles Rams,19,Vince Ferragamo
40,XIII,1979,AFC,AFC North,Pittsburgh Steelers,35,Terry Bradshaw,MVP,Orange Bowl,Miami,FL,NFC,NFC East,Dallas Cowboys,31,Roger Staubach
41,XII,1978,NFC,NFC East,Dallas Cowboys,27,Roger Staubach,,Louisiana Superdome,New Orleans,LA,AFC,AFC West,Denver Broncos,10,Craig Morton
42,XI,1977,AFC,AFC West,Oakland Raiders,32,Ken Stabler,,Rose Bowl,Pasadena,CA,NFC,NFC North,Minnesota Vikings,14,Fran Tarkenton
43,X,1976,AFC,AFC North,Pittsburgh Steelers,21,Terry Bradshaw,,Orange Bowl,Miami,FL,NFC,NFC East,Dallas Cowboys,17,Roger Staubach
44,IX,1975,AFC,AFC North,Pittsburgh Steelers,16,Terry Bradshaw,,Tulane Stadium,New Orleans,LA,NFC,NFC North,Minnesota Vikings,6,Fran Tarkenton
45,VIII,1974,AFC,AFC East,Miami Dolphins,24,Bob Griese,,Rice Stadium,Houston,TX,NFC,NFC North,Minnesota Vikings,7,Fran Tarkenton
46,VII,1973,AFC,AFC East,Miami Dolphins,14,Bob Griese,,Los Angeles Memorial Coliseum,Los Angeles,CA,NFC,NFC East,Washington Redskins,7,Billy Kilmer
47,VI,1972,NFC,NFC East,Dallas Cowboys,24,Roger Staubach,MVP,Tulane Stadium,New Orleans,LA,AFC,AFC East,Miami Dolphins,3,Bob Griese
48,V,1971,AFC,,Baltimore Colts,16,Johnny Unitas,,Orange Bowl,Miami,FL,NFC,NFC East,Dallas Cowboys,13,Craig Morton
49,IV,1970,AFC,AFC West,Kansas City Chiefs,23,Len Dawson,MVP,Tulane Stadium,New Orleans,LA,NFC,NFC North,Minnesota Vikings,7,Joe Kapp
50,III,1969,AFC,AFC East,New York Jets,16,Joe Namath,MVP,Orange Bowl,Miami,FL,NFC,,Baltimore Colts,7,Earl Morrall
51,II,1968,NFC,NFC North,Green Bay Packers,33,Bart Starr,MVP,Orange Bowl,Miami,FL,AFC,AFC West,Oakland Raiders,14,Daryle Lamonica
52,I,1967,NFC,NFC North,Green Bay Packers,35,Bart Starr,MVP,Los Angeles Memorial Coliseum,Los Angeles,CA,AFC,AFC West,Kansas City Chiefs,10,Len Dawson